parameters:
  archType: ''
  buildConfig: ''
  container: ''
  dependOnEvaluatePaths: false
  isOfficialBuild: false
  osGroup: ''
  osSubgroup: ''
  platform: ''
  pool: ''
  runtimeVariant: ''
  stagedBuild: false
  testGroup: ''
  timeoutInMinutes: ''
  variables: {}

jobs:
- template: xplat-pipeline-job.yml
  parameters:
    archType: ${{ parameters.archType }}
    buildConfig: ${{ parameters.buildConfig }}
    container: ${{ parameters.container }}
    condition: ${{ parameters.isOfficialBuild }}
    helixType: 'build/product/'
    osGroup: ${{ parameters.osGroup }}
    osSubgroup: ${{ parameters.osSubgroup }}
    pool: ${{ parameters.pool }}
    runtimeVariant: ${{ parameters.runtimeVariant }}
    stagedBuild: ${{ parameters.stagedBuild }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    dependOnEvaluatePaths: ${{ parameters.dependOnEvaluatePaths }}

    name: workloadsbuild
    displayName: Build Workloads

    variables:
    - name: officialBuildIdArg
      value: ''
    - ${{ if and(eq(variables['System.TeamProject'], 'internal'), ne(variables['Build.Reason'], 'PullRequest')) }}:
      - name: officialBuildIdArg
        value: '/p:OfficialBuildId=$(Build.BuildNumber)'
    - name: SignType
      value: $[ coalesce(variables.OfficialSignType, 'real') ]
    - ${{ parameters.variables }}

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: 'internal'
        pipeline: 679
        runVersion: 'specific'
        runId: 1217582
        artifact: 'IntermediateArtifacts'
        path: $(workloadPackagesPath)
        patterns: 'IntermediateArtifacts/*/Shipping/*.nupkg'

    - task: CopyFiles@2
      displayName: Flatten packages
      inputs:
        sourceFolder: $(workloadPackagesPath)
        contents: '*/Shipping/*.nupkg'
        cleanTargetFolder: false
        targetFolder: $(workloadPackagesPath)
        flattenFolders: true

    - script: $(Build.SourcesDirectory)$(dir)build$(scriptExt) -subset mono.workloads -arch $(archType) $(osArg) -c $(buildConfig) $(officialBuildIdArg) -ci
      displayName: Build workload artifacts

    # Upload packages wrapping msis
    - template: /eng/pipelines/common/upload-intermediate-artifacts-step.yml
      parameters:
        name: workloads

    # Delete wixpdb files before they are uploaded to artifacts
    - task: DeleteFiles@1
      displayName: Delete wixpdb's
      inputs:
        SourceFolder: $(workloadArtifactsPath)
        Contents: '*.wixpdb'

    # Upload artifacts to be used for generating VS components
    - task: PublishPipelineArtifact@1
      displayName: Publish workload artifacts
      inputs:
        targetPath: $(workloadArtifactsPath)
        artifactName: 'Workloads'
      continueOnError: true
      condition: always()
